### PR TITLE
Add RTAS Stats 2010-2022

### PR DESCRIPTION
**Pull request by mnwrhsn**

### CODE REVIEW

**Review by mnwrhsn — COMMENTED** [review]
Change to "BED" as you suggested!

**Comment by emeryberger** [comment]
Please update the Source columns to point to the document that is the source of the statistics.

**Comment by mnwrhsn** [comment]
> Please update the Source columns to point to the document that is the source of the statistics.

Done!

**Comment by emeryberger** [comment]
I don't think this is authoritative data, is it? I am looking for links to proceedings front matter.

**Comment by mnwrhsn** [comment]
This database is maintained by TCRTS (https://cmte.ieee.org/tcrts/) [Conferences—> Conference Statistics] — I suppose this should be accurate. I can change source link to IEEEXplore FM if that helps.

**Comment by emeryberger** [comment]
The sheet feels sketchy and it's clearly incomplete. Hopefully the front matter links will contain all the details, including all recent iterations. Thanks.

**Comment by mnwrhsn** [comment]
Change src with IEEEXplore FM for both RTSS & RTAS.

**Comment by emeryberger** [comment]
Almost! I'm looking for links like this: https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9355549 (where one click takes you directly to the information).

**Comment by mnwrhsn** [comment]
Done!

**Comment by emeryberger** [comment]
SO CLOSE :). I see there is some confusion about Sequence - that number should for this conference always be 1 (there's just 1 a year) and it should appear after the year.

**Comment by emeryberger** [comment]
Rows should follow this header (Sequence is out of order; it needs to follow Year):
`Area,Conference,Year,Sequence,Accepted,Submitted,Source,Notes`

**Comment by mnwrhsn** [comment]
Ah, I missed that on my editor. Fixed now.

**Comment by emeryberger** [comment]
LGTM - thanks!

**Pull request merged**
